include /env.mak

obj-m += cedarview-synobios.o

cedarview-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds1512+.o \
	ds1513+.o \
	ds412+.o \
	rs812+.o \
	rs812rp+.o \
	rs814+.o \
	rs814rp+.o \
	ds1812+.o \
	ds1813+.o \
	rs2212+.o \
	rs2212rp+.o \
	rs2414+.o \
	rs2414rp+.o \
	ds2413+.o \
	ds713+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	cedarview_common.o
