include /env.mak

obj-m += purley-synobios.o

purley-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	fs6400.o \
	fs6500.o \
	sa6500.o \
	hd6500.o \
	fs6600n.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	purley_common.o \
	../led/led_trigger.o \
	../i2c/i2c-linux.o \
	../led/led_gpio.o \
	../switchtec/switchtec.o \
	../pmbus/pmbus.o
