include /env.mak

obj-m += geminilake-synobios.o

geminilake-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds420p.o \
	ds720p.o \
	ds1520p.o \
	ds220p.o \
	ds920p.o \
	dva1622.o \
	ds423p.o \
	ds224p.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	geminilake_common.o \
	../led/led_trigger.o
