obj-m += evansport-synobios.o

evansport-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds214play.o \
	ds415play.o \
	ds114+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	evansport_common.o
