include /env.mak

obj-m += broadwellnkv2-synobios.o

broadwellnkv2-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs4022xs+.o \
	fs3410.o \
	sa3410.o \
	sa3610.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	../led/led_trigger.o \
	broadwellnkv2_common.o \
	../pmbus/pmbus.o
