obj-$(CONFIG_SYNO_DM_FLASHCACHE) += flashcache_syno.o
flashcache_syno-objs := flashcache_conf.o flashcache_main.o flashcache_subr.o flashcache_ioctl.o flashcache_procfs.o syno_functions.o syno_kernel_functions.o syno_quickflush.o syno_md_update.o
