include /env.mak

obj-m += broadwellntb-synobios.o

broadwellntb-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	taipei.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	broadwellntb_common.o
