include /env.mak

obj-m += r1000-synobios.o

r1000-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds723p.o \
	ds923p.o \
	rs422p.o \
	ds1522p.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	r1000_common.o \
	../led/led_trigger.o
