include /env.mak

obj-m += avoton-synobios.o

avoton-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds2415+.o \
	ds415+.o \
	ds1815+.o \
	ds1515+.o \
	rs815+.o \
	rs815rp+.o \
	rs2416+.o \
	ds1616+.o \
	rs2416rp+.o \
	ds1517+.o \
	ds1817+.o \
	rs818+.o \
	rs818rp+.o \
	rs1219+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	avoton_common.o
