include /env.mak

obj-m += icelaked-synobios.o

icelaked-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs4023xs+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-pericom-lib.o \
	../rtc/rtc-linux-pericom.o \
	../i2c/i2c-linux.o \
	icelaked_common.o \
	../led/led_trigger.o
