include /env.mak

obj-m += v1000-synobios.o

v1000-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds1621p.o \
	rs1221p.o \
	rs1221rp+.o \
	ds1821p.o \
	ds2422p.o \
	rs2421p.o \
	rs2421rpp.o \
	rs2821rpp.o \
	fs2500.o \
	fs2500t.o \
	rs822p.o \
	rs822rpp.o \
	rs2423p.o \
	rs2423rpp.o \
	ds1823xsp.o \
	rs1623xsp.o \
	ds1623p.o \
	ds1823p.o \
	sc2500.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	v1000_common.o \
	../led/led_trigger.o \
	../led/led_jmb585.o \
	../led/led_asm116x.o \
	../led/led_1475.o \
	../pmbus/pmbus.o
