include /env.mak

obj-m += bromolow-synobios.o

bromolow-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs3412rpxs.o \
	rs3412xs.o \
	ds3612xs.o \
	ds3615xs.o \
	rs3411rpxs.o \
	rs3411xs.o \
	ds3611xs.o \
	rs10613xs+.o \
	rs3413xs+.o \
	rs3614xs.o \
	rs3614rpxs.o \
	rs3614xs+.o \
	ds2414xs.o \
	rs3415xs+.o \
	rc18015xs+.o \
	rs18016xs+.o \
	rs3617xs.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	bromolow_common.o
