include /env.mak

obj-m += braswell-synobios.o

braswell-synobios-objs = \
       ../common/common.o \
       ../syno_ttyS/syno_ttyS.o \
       ../synobios.o \
       ds916p.o \
	   ds716+.o \
	   ds216+.o \
	   ds216+II.o \
	   ds416play.o \
	   ds716+II.o \
       ../mapping.o \
       ../rtc/localtime.o \
       ../rtc/alarmtime.o \
       ../rtc/rtc-x86.o \
       ../i2c/i2c-linux.o \
       braswell_common.o
