include /env.mak

obj-m += broadwellntbap-synobios.o

broadwellntbap-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	sa3200d.o \
	sa3400d.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	broadwellntbap_common.o
