include /env.mak

obj-m += coffeelake-synobios.o

coffeelake-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	ds3619xs.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	../common/common.o \
	coffeelake_common.o
