include /env.mak

obj-m += epyc7003ntb-synobios.o

epyc7003ntb-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	../led/led_trigger.o \
	../pmbus/pmbus.o \
	epyc7003ntb_common.o \
	fs6600dn.o \
