include /env.mak

obj-m += grantley-synobios.o

grantley-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs18016dxs+.o \
	fs3017.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	grantley_common.o
