include /env.mak

obj-m += broadwell-synobios.o

broadwell-synobios-objs = \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs4017xs+.o \
	rs18017xs+.o \
	rsd18016xs+.o \
	rs3618xs.o \
	rs3617rpxs.o \
	rs3617xs+.o \
	ds3617xs.o \
	fs2017.o \
	ds3017xs.o \
	fs3400.o \
	ds3617xsII.o \
	ds3622xs+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-x86.o \
	../i2c/i2c-linux.o \
	broadwell_common.o
