include /env.mak

obj-m += epyc7002sofs-synobios.o

epyc7002sofs-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	../led/led_trigger.o \
	../pmbus/pmbus.o \
	epyc7002sofs_common.o \
	fs6400n.o \
	fs6410.o \
	sa6400.o \
	sa6200.o \
	sc6200.o
